### ISSUE TITLE
Suggestions for content.

### ISSUE THREAD

**Issue by alpha74** [iiit-nagpur/Suggestion-Box#3]
We should create a something like a flow of content. The content should be like what we have learnt till now in our college courses, and collecting relevant material for the same.

**Comment by parthw1** [comment]
How should be the structure of the repository? Please suggest.

**Comment by kunalyelne** [comment]
Structure of the repository : 1) It should have semester wise content or year wise content or projects
                                                  OR
                                                2) Beginner/Intermediate/ Advanced
We can have competitive coding repository , final year projects repository, etc etc

**Comment by parthw1** [comment]
Yes! Looks good. @mrselukar @alpha74 what do you suggest?

**Comment by alpha74** [comment]
Directory structure:
Level1:
sands_of_time
Level2: inside_sands_of_time
>sands_of_comp_arch
>sands_of_oops
Level3: inside sands_of_comp_arch
>books
>material
>ques_papers

This is the proposed structure and is subject to change.

**Comment by parthw1** [comment]
A section for project ideas can also be added in the level3 ;)

**Comment by alpha74** [comment]
Yes, it can be chagned
